from typing import Protocol, Any, List

class AbstractRepository(Protocol):
    def create(self, entity_name: str, data: dict) -> Any: ...
    def get(self, entity_name: str, item_id: str) -> dict: ...
    def list(self, entity_name: str) -> List[dict]: ...
    def update(self, entity_name: str, item_id: str, data: dict) -> dict: ...
    def delete(self, entity_name: str, item_id: str) -> None: ...
